# Generated by Django 3.1.3 on 2020-11-20 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='image',
            field=models.ImageField(default='images/home-profile.jpg', upload_to='images/'),
        ),
    ]
