# Generated by Django 3.1.3 on 2020-11-20 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='images/home-profile.jpg', upload_to='images/')),
                ('name', models.CharField(max_length=30)),
                ('field', models.CharField(max_length=30)),
                ('topic', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=300)),
                ('ToBeLearned', models.CharField(max_length=300)),
                ('requirements', models.CharField(max_length=300)),
                ('ToBeCovered', models.CharField(max_length=300)),
                ('level', models.CharField(max_length=30)),
                ('instructor', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('course', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('image', models.ImageField(default='images/home-profile.jpg', upload_to='images/')),
                ('name', models.CharField(max_length=30)),
                ('videos', models.FileField(upload_to='videos/')),
                ('extras', models.FileField(upload_to='extras/')),
                ('course', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('section', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.section')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=100)),
                ('course', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('reviewed_by', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Enrolled',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('enrollee', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
